### PR TITLE
Enhancement: Update imaging icons

### PR DESCRIPTION
**Pull request by khornberg**
Use community icons
[private]

### CODE REVIEW

**Comment by khornberg** [comment]
This inlines the svg of the icons changed in #1. 

The result is:
fileuserskyleprojectsiconsjesiconshtml-full

**Comment by khornberg** [comment]
@jes-smith @jthatcher1293 Can both of you look to make sure the correct icons were added?

**Comment by mordorunicorn** [comment]
@khornberg They look right to me

**Comment by mordorunicorn** [comment]
@khornberg I just looked at my local imaging and realized I was wrong in my last comment. The one for a plain file looks right, but the other file types are like the negative version of what's here.

**Comment by khornberg** [comment]
Which ones are wrong?

**Comment by khornberg** [comment]
@jthatcher1293 Where did you get the outlined ones? I could not find them.

Last changes makes them the same size and color as the other icons.

image

**Comment by mordorunicorn** [comment]
@khornberg I `inspected` them when I ran imaging locally and copied them from there

**Comment by khornberg** [comment]
what is the source that imaging uses?

**Comment by khornberg** [comment]
Ok, I see that you grabbed the font awesome icon.
Did we want to mix font awesome or try to keep to material icons and it's community icons?

Community material icon on left | font awesome on right - both zoomed
image

Slightly different. The question is does one or the other more fit in to the over all set.

**Comment by khornberg** [comment]
@jes-smith thoughts on ☝️

**Comment by jes-smith** [comment]
@khornberg I will contact you offline to discuss this.

**Comment by khornberg** [comment]
Closing this. The ideas will be included in the styleguide at some point

**Pull request closed without merging**
